@startuml
title 4G EPS-AKA Authentication

participant UE
participant eNB
participant MME
participant HSS

UE -> eNB: Attach Request
eNB -> MME: Initial UE Message

MME -> HSS: Auth Info Request
HSS -> MME: Auth Info Response

MME -> UE: Auth Request
UE -> MME: Auth Response

@enduml
