@startuml
title Basic EN-DC (LTE Macro + NR Mid-Band on Same Site)
actor UE
participant LTE as "eNB (Master Node)"
participant NR as "gNB (Secondary Node)"

UE -> LTE: RRC Connection Setup
LTE -> NR: EN-DC Addition Request (X2/Xn)
NR -> LTE: EN-DC Addition Request Ack
LTE -> UE: RRC Reconfiguration (Add NR)
UE -> NR: RRC Connection Setup
UE -> LTE: RRC Reconfiguration Complete
LTE -> NR: Data Split Activated
@enduml