@startuml
title LTE + NR DSS (Dynamic Spectrum Sharing)

actor UE
participant LTE_NR as "DU (LTE+NR DSS)"

UE -> LTE_NR: RRC Connection Setup
LTE_NR -> UE: RRC Connection Setup Complete
UE -> LTE_NR: Measurement Reports
LTE_NR -> UE: RRC Reconfiguration (Activate NR)
UE -> LTE_NR: RRC Reconfiguration Complete
LTE_NR -> UE: PDCP Split Activated
@enduml
